format = """
[╭─](bold blue)$os$username$hostname$directory$git_branch$git_status
[╰─](bold blue)$character"""

[os]
disabled = false
style = "bold blue"

[username]
style_user = "bold cyan"
style_root = "bold red"
show_always = true
format = "[$user]($style)[@](white)"

[hostname]
ssh_only = false
style = "bold cyan"
format = "[$hostname]($style) "

[directory]
style = "bold blue"
truncation_length = 3
format = "in [$path]($style) "

[git_branch]
style = "bold purple"
format = "on [$symbol$branch]($style) "

[git_status]
style = "bold red"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
