preload = /home/gustavosp/Imagens/Wallpapers/abstract-blue.png
wallpaper = DP-3,/home/gustavosp/Imagens/Wallpapers/abstract-blue.png
wallpaper = HDMI-A-1,/home/gustavosp/Imagens/Wallpapers/abstract-blue.png
splash = false
