background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
}

input-field {
    monitor =
    size = 250, 60
    outline_thickness = 3
    dots_size = 0.3
    dots_spacing = 0.2
    outer_color = rgba(88c0d0ee)
    inner_color = rgba(46, 52, 64, 0.8)
    font_color = rgb(236, 239, 244)
    placeholder_text = Digite a senha
    position = 0, -150
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(236, 239, 244, 1)
    font_size = 64
    position = 0, 100
    halign = center
    valign = center
}
